### ISSUE TITLE
Unify job declaration syntax between regular group and pipelines

### ISSUE THREAD

**Issue by stormbeta** [ReadyTalk/jenkins-pipeline-dsl#2]
Right now, job declarations in pipeline blocks and in the base context have flipped syntax. It would be a lot less confusing to use the same syntax for both.

A couple options:

**1. Make everything work like pipeline job definitions**

``` yaml
- job-name:
    type: gradleProject
- pipeline:
    build:
      type: gradleProject
```

This is the simplest way to achieve consistency, but it's a bit less semantically consistent (user data string in the same scope as strings referring to dsl type names).

**2. Make everything work like regular job definitions**

``` yaml
- gradleProject:
    name: job-name
- pipeline:
    gradleProject:
      name: build
```

This is more semantically equivalent, but it becomes confusing because "name" is actually supposed to refer to a stage.

**3. Compromise syntax:**

``` yaml
- gradleProject:
    name: job-name
- pipeline:
    gradleProject:
      stage: build
```

The idea here is that "name" can actually be omitted entirely, without conflating different types of things in the same scope. This would also allow overriding the name created by the pipeline if desired. It's also one way of enabling multiple jobs per stage.

The caveat is that it complicates implementation, though this can be somewhat mitigated by making the groovy version of the dsl more like the yaml version (while maintaining backwards-compatibility):

``` groovy
gradleProject(name: 'job-name')
//or
gradleProject {
  name = 'job-name'
}
//or
gradleProject('job-name')
```
